import {Food} from './shared/models/Food';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: '義式臘腸pizza',
    cookTime: '10-20',
    price: 500,
    favorite: false,
    origins: ['義大利'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['速食', 'Pizza', '午餐'],
  },
  {
    id:'2',
    name: '肉丸',
    price: 120,
    cookTime: '20-30',
    favorite: true,
    origins: ['中東', '中國', '亞洲'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['小吃'],
  },
  {
    id:'3',
    name: '漢堡',
    price: 210,
    cookTime: '10-15',
    favorite: false,
    origins: ['德國', '美國'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['速食', '漢堡', '午餐'],
  },
  {
    id:'4',
    name: '薯條',
    price: 80,
    cookTime: '15-20',
    favorite: true,
    origins: ['法國'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['速食', '炸物', '小吃'],
  },
  {
    id:'5',
    name: '雞湯',
    price: 60,
    cookTime: '40-50',
    favorite: false,
    origins: ['印度', '亞洲'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: '蔬食pizza',
    price: 350,
    cookTime: '40-50',
    favorite: false,
    origins: ['義大利'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['速食', 'Pizza', '午餐'],
  },
]
